[project]
name = "g7-openarm-mpc-vel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cffi>=2.0.0",
    "matplotlib>=3.10.8",
    "mujoco>=3.7.0",
    "pip>=26.1.1",
    "unitree-sdk2py",
]

[tool.uv.sources]
unitree-sdk2py = { path = "third_party/unitree_sdk2_python", editable = true }
